# config.py

# Замените старый URL на этот:
CAMERA_URL = "http://192.168.0.100:81/stream"
DATABASE_PATH = "fare_enforcement.db"
SERIAL_PORT = "/dev/ttyACM0"
SERIAL_BAUD_RATE = 115200
FACE_MATCH_THRESHOLD = 0.6
EXIT_DEBOUNCE_SECONDS = 15
ROUTE_ID = "UNASSIGNED_ROUTE"
FINE_AMOUNT = 0.0
CAMERA_ROLE = "entry"  # Set to "exit" for the exit camera.
UNKNOWN_FACE_DIR = "unknown_faces"
UNKNOWN_CAPTURE_INTERVAL_SEC = 2
INSIGHTFACE_MODEL = "buffalo_l"

# Остальные настройки можно оставить как есть
FRAME_WIDTH = 320
FRAME_HEIGHT = 240
FACE_DETECTION_CONFIDENCE = 0.5
RECOGNITION_THRESHOLD = FACE_MATCH_THRESHOLD
SESSION_TIMEOUT_SEC = 300
RECONNECT_DELAY_SEC = 5
PAYMENT_API_HOST = "0.0.0.0"
PAYMENT_API_PORT = 8080
